import type { NextPage } from 'next'
import Head from 'next/head'
import styles from './Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='text-5xl text-green-500'>Hello World!</h1>
      </main>
    </>
  )
}

export default Home
