import type {NextPage} from 'next';

import Head from 'next/head';
import Hero from '../components/home/Hero';
import HowItWorks from '../components/home/HowItWorks';
import OurCollection from '../components/home/OurCollection';
import WhyUs from '../components/home/WhyUs';
import Nav from '../components/Nav';

import styles from './Home.module.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon-32x32.png' />
      </Head>

      <Nav />

      <main>
        <Hero />
        <OurCollection />
        <WhyUs />
        <HowItWorks />
      </main>
    </>
  );
};

export default Home;
